---
version: "2.0"
services:
  api:
    image: baktun/test-multi-service-api:1.0.5
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
    env:
      - URL_SERVICE=http://service:3001
  service:
    image: baktun/test-multi-service-service:1.0.1
    expose:
      - port: 3001
        as: 3001
        to:
          - service: api
profiles:
  compute:
    api:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 512Mb
    service:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 512Mi
  placement:
    dcloud:
      pricing:
        api:
          denom: uakt
          amount: 1000
        service:
          denom: uakt
          amount: 1000
deployment:
  api:
    dcloud:
      profile: api
      count: 1
  service:
    dcloud:
      profile: service
      count: 1
